### PR TITLE
Adding an icon to the menu item and remove extra slash

### PR DESCRIPTION
**Pull request by circlecube**

### CODE REVIEW

**Comment by Shelob9** [comment]
Thanks @circlecube !

**Comment by circlecube** [comment]
Sure, np! 

I'm still thinking through the ui too. I'm wondering if adding a pager of sorts to indicate what revision is currently displayed would be helpful. I could see a number of additions that might be helpful, but not sure if they're warranted. Like a button to restore the revision currently viewed, another link that's visible once you've left the latest revision that will jump you back to current, could easily add arrows to the previous and next links (but not sure if that's against the style guide of WP, since there are no other sub links with icons). I'd be happy to jump on any of these ideas if you deem them promising.

**Comment by Shelob9** [comment]
I don't think arrows are likely to be considered correct for core UI...

Jump back to current is a great idea.

Also, we should probably check, server-side if there are revisions and if not don't even bother loading...

**Comment by circlecube** [comment]
OK, I can do those today I think.

**Pull request merged**
